sudo: required
services:
  - docker

before_install:
  - docker build -t wwkkww/node-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wwkkww/node-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-southeast-1"
  app: "docker-node-react-nginx"
  env: "DockerNodeReactNginx-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-031203145391"
  bucket_path: "docker-node-react-nginx"
  on:
    branch: master